[project]
authors = ["shivasankar <shivasankar.ka@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Implementation of basic ML algorithms using NuMojo"
name = "MLalgorithms"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.6.0,<25"
numpy = ">=1.26.4,<2"
matplotlib = ">=3.10.0,<4"
scikit-learn = ">=1.6.0,<2"
