[project]
authors = ["shivasankar <shivasankar.ka@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Implementation of basic ML algorithms using NuMojo"
name = "MLalgorithms"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
numpy = "<2.0"
matplotlib = ">=3.9.2,<4"
scikit-learn = ">=1.5.2,<2"
